name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events on all branches
  push

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Make entrypoint.sh executable
        run: chmod +x entrypoint.sh
      - 
        name: Build HTML
        uses: docker://mtreber/capella-html-exporter:5.1.0-0
        
